AWSTemplateFormatVersion: 2010-09-09

Parameters:
  clusterIndex:
    Type: Number
  PrivateSubnet:
    Type: String
  SshIpCidr:
    Type: String
  VpcId:
    Type: String
  KeyPair:
    Type: String
  isDev:
    Type: String
  numberOfClusters:
    Type: Number
  DiscordToken:
    Type: String
  DiscordClientId:
    Type: String

Resources:

  ############################
  # Cluster Ec2
  ############################
        
  SshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SshIpCidr
        
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08116b9957a259459
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds: 
        - !Ref SshSecurityGroup
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          sudo -u ubuntu sh -c 'sudo apt update -y'
          sudo -u ubuntu sh -c 'sudo apt upgrade -y'
          sudo -u ubuntu sh -c 'sudo apt install -y curl'
          sudo -u ubuntu sh -c 'sudo apt install -y ffmpeg=7:4.4.2-0ubuntu0.22.04.1'
          sudo -u ubuntu sh -c 'curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -'
          sudo -u ubuntu sh -c 'sudo apt install -y nodejs'
          sudo -u ubuntu sh -c 'sudo npm install pm2 -g'
          sudo -u ubuntu sh -c 'sudo git clone https://github.com/Broken-GM/Bot.git ./home/ubuntu/Bot'
          sudo -u ubuntu sh -c 'sudo chmod +x ./home/ubuntu/Bot/deploy-development.sh'
          sudo -u ubuntu sh -c 'sudo chmod +x ./home/ubuntu/Bot/generate-ecosystem.sh'
          sudo -u ubuntu sh -c 'sudo chmod +x ./home/ubuntu/Bot/start-app.sh'
          sudo -u ubuntu sh -c './home/ubuntu/Bot/generate-ecosystem.sh ${DiscordToken} ${DiscordClientId} ${numberOfClusters} ${clusterIndex}'
          sudo -u ubuntu sh -c './home/ubuntu/Bot/start-app.sh'

Outputs:
  InstanceId:
    Description: EC2 Instance Id
    Value: !Ref EC2Instance