AWSTemplateFormatVersion: 2010-09-09

Resources:
  ############################
  # VPC Infrastructure
  ############################

  BotNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SourceDestCheck: 'false'
      GroupSet:
        - !Ref BotInstanceSecurityGroup
      SubnetId: !Ref BotPrivateSubnet

  BotInstanceEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt BotElasticIp.AllocationId
      NetworkInterfaceId: !Ref BotNetworkInterface
      PrivateIpAddress: 10.0.4.10

  BotInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t4g.nano
      KeyName: EC2 Keys
      ImageId: ami-0c79a55dda52434da
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref BotNetworkInterface
          DeviceIndex: 0

  BotInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref BotVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SshIpCidr
        

Outputs:
  IpAddress:
    Description: Ip Address
    Value: !Ref BotElasticIp

  SecurityGroupId:
    Description: SecurityGroupId for Bot VPC
    Value: !GetAtt BotVpc.DefaultSecurityGroup

  SubnetId:
    Description: SubnetId for Bot VPC
    Value: !Ref BotPrivateSubnet