AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PrivateSubnet:
    Type: String
  SshIpCidr:
    Type: String
  VpcId:
    Type: String
  KeyPair:
    Type: String

Resources:

  ############################
  # Cluster Ec2
  ############################
        
  SshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SshIpCidr
        
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08116b9957a259459
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds: 
        - !Ref SshSecurityGroup
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo -u ubuntu sh -c 'sudo apt update -y'
          sudo -u ubuntu sh -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
          sudo -u ubuntu sh -c 'sudo apt -y upgrade'
          sudo -u ubuntu sh -c 'sudo apt install -y ffmpeg'
          sudo -u ubuntu sh -c 'export NVM_DIR="$([ -z "${!XDG_CONFIG_HOME-}" ] && printf %s "${!HOME}/.nvm" || printf %s "${!XDG_CONFIG_HOME}/nvm")"''
          sudo -u ubuntu sh -c '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"''
          sudo -u ubuntu sh -c 'nvm install 20'
          sudo -u ubuntu sh -c 'nvm use 20'